---
- name: Copy config files
  template: src="{{ item.src }}" dest="{{ item.dst }}"
  mode: 0600
  with_items:
    - src: xl2tpd.conf.j2
      dst: /etc/xl2tpd/xl2tpd.conf
    - src: options.xl2tpd.j2
      dst: /etc/ppp/options.xl2tpd
    - src: chap-secrets
      dst: /etc/ppp/chap-secrets

- name: restart xl2tpd
  service: name=xl2tpd state=restarted enabled=yes
