---
- name: Install packages
  hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - set_fact:
        tls_cert: "/etc/pki/tls/certs/{{my_hostname}}.crt"
        tls_key: "/etc/pki/tls/private/{{my_hostname}}.key"
      tags: ['stunnel']

  tasks:
    - name: Install epel
      yum: name=epel-release state=latest
    - name: ensure a list of packages installed
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - stunnel
          - squid
          - httpd-tools


    - stat: path={{tls_cert}}
      register: stc

    - stat: path={{tls_key}}
      register: stk

    - fail:
        msg: "Certificate file {{tls_cert}} not exists"
      when: not stc.stat.exists
    - fail:
        msg: "Key file {{tls_key}} not exists"
      when: not stk.stat.exists

    - debug:
        msg: "Using {{tls_cert}} and {{tls_key}}"


    - shell: |
        ip a show dev eth0 | sed -nre 's|.*inet ([\.0-9]+)/[0-9]+.*|\1|p'
      register: ipret

    - set_fact:
        my_ip: "{{ipret.stdout}}"

    - debug:
        msg: "Add {{my_ip}} {{my_hostname}} in /etc/hosts"

    - lineinfile:
        path: /etc/hosts
        line: "{{my_ip}} {{my_hostname}}"
        regexp: '^{{my_ip}}'

  roles:
    - role: squid
    - role: stunnel
      tags: ['stunnel']
