---
- name: Install packages
  hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Install epel
      yum: name=epel-release state=latest
    - name: ensure a list of packages installed
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - stunnel
        - squid
        - httpd-tools

    - copy: src={{src_cert}} dest={{tls_cert}}
    - copy: src={{src_key}} dest={{tls_key}}

  roles:
    - squid
    - stunnel
