---
- name: Install packages
  hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Install epel
      yum: name=epel-release state=latest
    - name: ensure a list of packages installed
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - stunnel
        - squid
        - httpd-tools

    - stat: path={{tls_cert}}
      register: stc
    - stat: path={{tls_key}}
      register: stk
    - copy: src={{src_cert}} dest={{tls_cert}}
      when: not stc.stat.exists
    - copy: src={{src_key}} dest={{tls_key}}
      when: not stk.stat.exists

    - shell: |
        ip a show dev eth0 | sed -nre 's|.*inet ([\.0-9]+)/[0-9]+.*|\1|p'
      register: ipret
    - setup_fact:
        my_ip: "{{ipret.stdout}}"
    - debug:
        msg: "Add {{my_ip}} {{my_hostname}} in /etc/hosts"

    - lineinfile:
        path: /etc/hosts
        line: "{{my_ip}} {{my_hostname}}"
        regexp: '^{{my_ip}}'

  roles:
    - squid
    - stunnel
