---
- file: path=/var/log/stunnel.log owner=nobody group=nobody state=touch

- file: path=/var/run/stunnel owner=nobody group=nobody state=directory

- template:
    src: stunnel.conf
    dest: /etc/stunnel/stunnel.conf
    owner: nobody

- shell: |
    pkill stunnel
  ignore_errors: yes

- pause: seconds=5

- command: stunnel
