---
- name: add files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: preserve
  with_items:
    - src: stunnel.conf
      dest: /etc/stunnel/stunnel.conf
    - src: stunnel.service
      dest: /usr/lib/systemd/system/stunnel.service
    - src: stunnel.prev.sh
      dest: /usr/bin/stunnel.prev.sh
    - src: stunnel.post.sh
      dest: /usr/bin/stunnel.post.sh

- systemd:
    daemon_reload: yes
    enabled: yes
    name: stunnel
    state: restarted
