---
- name: Copy sysctl config files
  template: src="{{ item.src }}" dest="{{ item.dst }}"
  with_items:
    - src: etc/sysctl.d/ipsec.conf.j2
      dst: /etc/sysctl.d/88-ipsec.conf

- name: Reload sysctl.conf
  command: /sbin/sysctl -e -p
  register: rr

- debug: var=rr.stdout_lines
