- name: Disable firewalld
  service: name=firewalld state=stop enabled=no

- name: Copy scripts
  template: src=set-fw.sh.j2 dest=/tmp/set-fw.sh mode=0700

- script: /tmp/set-fw.sh

- name: Restart iptables
  service: name=iptables state=restarted enabled=yes
