---
- name: Install ipsec
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install epel
      yum: name=epel-release state=latest
    - name: upgrade all packages
      yum: name='*' state=latest
    - name: ensure a list of packages installed
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ RPM_DEPS }}"

- name: Install ipsec
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - xl2tpd
    - libreswan
