---
- name: Check variables
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - fail:
        msg: "Whoops! Please define variables in all.yml"
        when: ({{ VPN_IPSEC_PSK }} == '') or ({{ VPN_USER }} == '') or ({{VPN_PASSWORD}} == '')

- name: Install ipsec
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install epel
      yum: name=epel-release state=latest
    - name: upgrade all packages
      yum: name='*' state=latest
    - name: ensure a list of packages installed
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ RPM_DEPS }}"

    - name: Get default network interface
      script: "/sbin/ip route|egrep '^default'|sed 's/.*dev //'"
      register: rx

    - set_fact:
        net_iface: "{{ rx.stdout }}"

- name: Install xl2tpd and libreswan
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - sysctl
    - xl2tpd
    - libreswan
    - iptables
