---
- name: Check variables
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - fail: msg="VPN_IPSEC_PSK must non-empty"
      when: VPN_IPSEC_PSK == ''
    - fail: msg="VPN_USER must non-empty"
      when: VPN_USER == ''
    - fail: msg="VPN_PASSWORD must non-empty"
      when: VPN_PASSWORD == ''

- name: Install ipsec
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install epel
      yum: name=epel-release state=latest
    - name: upgrade all packages
      yum: name='*' state=latest
    - name: ensure a list of packages installed
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ RPM_DEPS }}"

    - name: Get default network interface
      script: "/sbin/ip route|egrep '^default'|sed 's/.*dev //'"
      register: rx

    - set_fact:
        net_iface: "{{ rx.stdout }}"
    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present

- name: Install xl2tpd and libreswan
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - sysctl
    - xl2tpd
    - libreswan
    - iptables
