---
- name: Install ipsec
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Install epel
      yum: name=epel-release state=latest
    - name: upgrade all packages
      yum: name='*' state=latest
    - name: ensure a list of packages installed
      yum:
        name: "{{ RPM_DEPS }}"
  vars_files:
    - ipsec.yml
