alias grep='egrep --color'
alias less='less -r'
alias psex='ps -ouser,pid,nlwp,ppid,start,etime,pcpu,pmem,rss,vsz,stat,tname,ucmd'
alias cscope-list='find . -name "cscope.*" | xargs ls -l'
alias cscope-del='find . -name "cscope.*" | xargs rm -f'
alias searchpkg='apt-cache search -n'
alias showpkg='apt-cache showpkg'
alias root='sudo su -'
alias nwemacs='emacs -nw'
alias dk='docker'
alias dkc='docker-compose'


alias maillog='tail -f /var/log/maillog'
alias syslog='tail -f /var/log/messages'
